// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_silver.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRowSilverCollaborators = `-- name: CreateRowSilverCollaborators :one
INSERT INTO silver.collaborators(id,
study_id,
name,
class, 
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (study_id,name)
DO UPDATE SET 
    class=EXCLUDED.class,
    updated_at=now()
RETURNING id, study_id, name, class, created_at, updated_at
`

type CreateRowSilverCollaboratorsParams struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Name      string
	Class     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverCollaborators(ctx context.Context, arg CreateRowSilverCollaboratorsParams) (SilverCollaborator, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverCollaborators,
		arg.ID,
		arg.StudyID,
		arg.Name,
		arg.Class,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverCollaborator
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.Name,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverInterventions = `-- name: CreateRowSilverInterventions :one
INSERT INTO silver.interventions(id,
study_id,
type,
name,
description,
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (study_id,name,type)
DO UPDATE SET 
    description=EXCLUDED.description,
    updated_at=now()
RETURNING id, study_id, type, name, description, created_at, updated_at
`

type CreateRowSilverInterventionsParams struct {
	ID          uuid.UUID
	StudyID     uuid.UUID
	Type        string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateRowSilverInterventions(ctx context.Context, arg CreateRowSilverInterventionsParams) (SilverIntervention, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverInterventions,
		arg.ID,
		arg.StudyID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverIntervention
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverLocations = `-- name: CreateRowSilverLocations :one
INSERT INTO silver.locations(id,
study_id,
city,
state,
country,
latitude,
longitude,
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (study_id, city,state,country)
DO UPDATE SET 
    latitude=EXCLUDED.latitude,
    longitude=EXCLUDED.longitude,
    updated_at=now()
RETURNING id, study_id, city, state, country, latitude, longitude, created_at, updated_at
`

type CreateRowSilverLocationsParams struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	City      sql.NullString
	State     sql.NullString
	Country   sql.NullString
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverLocations(ctx context.Context, arg CreateRowSilverLocationsParams) (SilverLocation, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverLocations,
		arg.ID,
		arg.StudyID,
		arg.City,
		arg.State,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverLocation
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.City,
		&i.State,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverOutcomes = `-- name: CreateRowSilverOutcomes :one
INSERT INTO silver.outcomes(id,
study_id,
measure,
timeframe,
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (study_id,measure)
DO UPDATE SET
    timeframe=EXCLUDED.timeframe,
    updated_at=now()
RETURNING id, study_id, measure, timeframe, created_at, updated_at
`

type CreateRowSilverOutcomesParams struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Measure   string
	Timeframe sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverOutcomes(ctx context.Context, arg CreateRowSilverOutcomesParams) (SilverOutcome, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverOutcomes,
		arg.ID,
		arg.StudyID,
		arg.Measure,
		arg.Timeframe,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverOutcome
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.Measure,
		&i.Timeframe,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverReferences = `-- name: CreateRowSilverReferences :one
INSERT INTO silver.references(id,
study_id,
pmid,
type,
citation,
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (study_id, citation)
DO UPDATE SET 
    pmid=EXCLUDED.pmid,
    type=EXCLUDED.type,
    updated_at=now()
RETURNING id, study_id, pmid, type, citation, created_at, updated_at
`

type CreateRowSilverReferencesParams struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Pmid      sql.NullString
	Type      sql.NullString
	Citation  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverReferences(ctx context.Context, arg CreateRowSilverReferencesParams) (SilverReference, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverReferences,
		arg.ID,
		arg.StudyID,
		arg.Pmid,
		arg.Type,
		arg.Citation,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverReference
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.Pmid,
		&i.Type,
		&i.Citation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverSponsors = `-- name: CreateRowSilverSponsors :one
INSERT INTO silver.sponsors(id,
study_id,
name,
class, 
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (study_id,name)
DO UPDATE SET 
    class=EXCLUDED.class,
    updated_at=now()
RETURNING id, study_id, name, class, created_at, updated_at
`

type CreateRowSilverSponsorsParams struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Name      string
	Class     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverSponsors(ctx context.Context, arg CreateRowSilverSponsorsParams) (SilverSponsor, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverSponsors,
		arg.ID,
		arg.StudyID,
		arg.Name,
		arg.Class,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverSponsor
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.Name,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverUpsertStudies = `-- name: CreateRowSilverUpsertStudies :one
INSERT INTO silver.studies (
    id,
    nct_id,
    condition,
    title,
    study_type,
    phase,
    enrollment,
    overall_status,
    start_date,
    start_date_precision,
    primary_completion_date,
    primary_completion_date_precision,
    completion_date,
    completion_date_precision,
    first_submit_date,
    first_submit_date_precision,
    last_update_submit_date,
    last_update_submit_date_precision,
    has_results,
    created_at,
    updated_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)
ON CONFLICT (nct_id)
DO UPDATE SET
    title = EXCLUDED.title,
    study_type = EXCLUDED.study_type,
    phase = EXCLUDED.phase,
    enrollment = EXCLUDED.enrollment,
    overall_status = EXCLUDED.overall_status,
    start_date = EXCLUDED.start_date,
    completion_date = EXCLUDED.completion_date,
    has_results = EXCLUDED.has_results,
    updated_at = now()
RETURNING id, nct_id, condition, title, study_type, phase, enrollment, overall_status, start_date, start_date_precision, primary_completion_date, primary_completion_date_precision, completion_date, completion_date_precision, first_submit_date, first_submit_date_precision, last_update_submit_date, last_update_submit_date_precision, has_results, created_at, updated_at
`

type CreateRowSilverUpsertStudiesParams struct {
	ID                             uuid.UUID
	NctID                          string
	Condition                      string
	Title                          sql.NullString
	StudyType                      sql.NullString
	Phase                          sql.NullString
	Enrollment                     sql.NullInt32
	OverallStatus                  sql.NullString
	StartDate                      sql.NullTime
	StartDatePrecision             sql.NullString
	PrimaryCompletionDate          sql.NullTime
	PrimaryCompletionDatePrecision sql.NullString
	CompletionDate                 sql.NullTime
	CompletionDatePrecision        sql.NullString
	FirstSubmitDate                sql.NullTime
	FirstSubmitDatePrecision       sql.NullString
	LastUpdateSubmitDate           sql.NullTime
	LastUpdateSubmitDatePrecision  sql.NullString
	HasResults                     sql.NullBool
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

func (q *Queries) CreateRowSilverUpsertStudies(ctx context.Context, arg CreateRowSilverUpsertStudiesParams) (SilverStudy, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverUpsertStudies,
		arg.ID,
		arg.NctID,
		arg.Condition,
		arg.Title,
		arg.StudyType,
		arg.Phase,
		arg.Enrollment,
		arg.OverallStatus,
		arg.StartDate,
		arg.StartDatePrecision,
		arg.PrimaryCompletionDate,
		arg.PrimaryCompletionDatePrecision,
		arg.CompletionDate,
		arg.CompletionDatePrecision,
		arg.FirstSubmitDate,
		arg.FirstSubmitDatePrecision,
		arg.LastUpdateSubmitDate,
		arg.LastUpdateSubmitDatePrecision,
		arg.HasResults,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.Title,
		&i.StudyType,
		&i.Phase,
		&i.Enrollment,
		&i.OverallStatus,
		&i.StartDate,
		&i.StartDatePrecision,
		&i.PrimaryCompletionDate,
		&i.PrimaryCompletionDatePrecision,
		&i.CompletionDate,
		&i.CompletionDatePrecision,
		&i.FirstSubmitDate,
		&i.FirstSubmitDatePrecision,
		&i.LastUpdateSubmitDate,
		&i.LastUpdateSubmitDatePrecision,
		&i.HasResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRowFromSilverStudiesByCondition = `-- name: GetRowFromSilverStudiesByCondition :one
SELECT id, nct_id, condition, title, study_type, phase, enrollment, overall_status, start_date, start_date_precision, primary_completion_date, primary_completion_date_precision, completion_date, completion_date_precision, first_submit_date, first_submit_date_precision, last_update_submit_date, last_update_submit_date_precision, has_results, created_at, updated_at FROM silver.studies WHERE condition = $1
`

func (q *Queries) GetRowFromSilverStudiesByCondition(ctx context.Context, condition string) (SilverStudy, error) {
	row := q.db.QueryRowContext(ctx, getRowFromSilverStudiesByCondition, condition)
	var i SilverStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.Title,
		&i.StudyType,
		&i.Phase,
		&i.Enrollment,
		&i.OverallStatus,
		&i.StartDate,
		&i.StartDatePrecision,
		&i.PrimaryCompletionDate,
		&i.PrimaryCompletionDatePrecision,
		&i.CompletionDate,
		&i.CompletionDatePrecision,
		&i.FirstSubmitDate,
		&i.FirstSubmitDatePrecision,
		&i.LastUpdateSubmitDate,
		&i.LastUpdateSubmitDatePrecision,
		&i.HasResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRowFromSilverStudiesByID = `-- name: GetRowFromSilverStudiesByID :one
SELECT id, nct_id, condition, title, study_type, phase, enrollment, overall_status, start_date, start_date_precision, primary_completion_date, primary_completion_date_precision, completion_date, completion_date_precision, first_submit_date, first_submit_date_precision, last_update_submit_date, last_update_submit_date_precision, has_results, created_at, updated_at FROM silver.studies WHERE id = $1
`

func (q *Queries) GetRowFromSilverStudiesByID(ctx context.Context, id uuid.UUID) (SilverStudy, error) {
	row := q.db.QueryRowContext(ctx, getRowFromSilverStudiesByID, id)
	var i SilverStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.Title,
		&i.StudyType,
		&i.Phase,
		&i.Enrollment,
		&i.OverallStatus,
		&i.StartDate,
		&i.StartDatePrecision,
		&i.PrimaryCompletionDate,
		&i.PrimaryCompletionDatePrecision,
		&i.CompletionDate,
		&i.CompletionDatePrecision,
		&i.FirstSubmitDate,
		&i.FirstSubmitDatePrecision,
		&i.LastUpdateSubmitDate,
		&i.LastUpdateSubmitDatePrecision,
		&i.HasResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRowFromSilverStudiesByNCTID = `-- name: GetRowFromSilverStudiesByNCTID :one
SELECT id, nct_id, condition, title, study_type, phase, enrollment, overall_status, start_date, start_date_precision, primary_completion_date, primary_completion_date_precision, completion_date, completion_date_precision, first_submit_date, first_submit_date_precision, last_update_submit_date, last_update_submit_date_precision, has_results, created_at, updated_at FROM silver.studies WHERE nct_id = $1
`

func (q *Queries) GetRowFromSilverStudiesByNCTID(ctx context.Context, nctID string) (SilverStudy, error) {
	row := q.db.QueryRowContext(ctx, getRowFromSilverStudiesByNCTID, nctID)
	var i SilverStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.Title,
		&i.StudyType,
		&i.Phase,
		&i.Enrollment,
		&i.OverallStatus,
		&i.StartDate,
		&i.StartDatePrecision,
		&i.PrimaryCompletionDate,
		&i.PrimaryCompletionDatePrecision,
		&i.CompletionDate,
		&i.CompletionDatePrecision,
		&i.FirstSubmitDate,
		&i.FirstSubmitDatePrecision,
		&i.LastUpdateSubmitDate,
		&i.LastUpdateSubmitDatePrecision,
		&i.HasResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
