// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_silver.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRowSilverCollaborators = `-- name: CreateRowSilverCollaborators :one
INSERT INTO silver.collaborators(id,
study_id,
name,
class, 
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (study_id,name)
DO UPDATE SET 
    class=EXCLUDED.class,
    updated_at=now()
RETURNING id, study_id, name, class, created_at, updated_at
`

type CreateRowSilverCollaboratorsParams struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Name      string
	Class     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverCollaborators(ctx context.Context, arg CreateRowSilverCollaboratorsParams) (SilverCollaborator, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverCollaborators,
		arg.ID,
		arg.StudyID,
		arg.Name,
		arg.Class,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverCollaborator
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.Name,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverDesignDetails = `-- name: CreateRowSilverDesignDetails :one
INSERT INTO silver.design_details(study_id,
allocation,
intervention_model,
primary_purpose,
masking,
created_at,
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (study_id)
DO UPDATE SET 
    allocation=EXCLUDED.allocation,
    intervention_model=EXCLUDED.intervention_model,
    primary_purpose=EXCLUDED.primary_purpose,
    masking=EXCLUDED.masking,
    updated_at=now()
RETURNING study_id, allocation, intervention_model, primary_purpose, masking, created_at, updated_at
`

type CreateRowSilverDesignDetailsParams struct {
	StudyID           uuid.UUID
	Allocation        sql.NullString
	InterventionModel sql.NullString
	PrimaryPurpose    sql.NullString
	Masking           sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateRowSilverDesignDetails(ctx context.Context, arg CreateRowSilverDesignDetailsParams) (SilverDesignDetail, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverDesignDetails,
		arg.StudyID,
		arg.Allocation,
		arg.InterventionModel,
		arg.PrimaryPurpose,
		arg.Masking,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverDesignDetail
	err := row.Scan(
		&i.StudyID,
		&i.Allocation,
		&i.InterventionModel,
		&i.PrimaryPurpose,
		&i.Masking,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverEligibility = `-- name: CreateRowSilverEligibility :one
INSERT INTO silver.eligibility(study_id,
sex,
std_ages,
created_at,
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (study_id)
DO UPDATE SET 
    sex=EXCLUDED.sex,
    std_ages=EXCLUDED.std_ages,
    updated_at=now()
RETURNING study_id, sex, std_ages, created_at, updated_at
`

type CreateRowSilverEligibilityParams struct {
	StudyID   uuid.UUID
	Sex       sql.NullString
	StdAges   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverEligibility(ctx context.Context, arg CreateRowSilverEligibilityParams) (SilverEligibility, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverEligibility,
		arg.StudyID,
		arg.Sex,
		arg.StdAges,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverEligibility
	err := row.Scan(
		&i.StudyID,
		&i.Sex,
		&i.StdAges,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverInterventions = `-- name: CreateRowSilverInterventions :one
INSERT INTO silver.interventions(id,
study_id,
type,
name,
description,
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (study_id,name,type)
DO UPDATE SET 
    description=EXCLUDED.description,
    updated_at=now()
RETURNING id, study_id, type, name, description, created_at, updated_at
`

type CreateRowSilverInterventionsParams struct {
	ID          uuid.UUID
	StudyID     uuid.UUID
	Type        string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateRowSilverInterventions(ctx context.Context, arg CreateRowSilverInterventionsParams) (SilverIntervention, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverInterventions,
		arg.ID,
		arg.StudyID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverIntervention
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverLocations = `-- name: CreateRowSilverLocations :one
INSERT INTO silver.locations(id,
study_id,
city,
state,
country,
latitude,
longitude,
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (study_id, city,state,country)
DO UPDATE SET 
    latitude=EXCLUDED.latitude,
    longitude=EXCLUDED.longitude,
    updated_at=now()
RETURNING id, study_id, city, state, country, latitude, longitude, created_at, updated_at
`

type CreateRowSilverLocationsParams struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	City      sql.NullString
	State     sql.NullString
	Country   sql.NullString
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverLocations(ctx context.Context, arg CreateRowSilverLocationsParams) (SilverLocation, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverLocations,
		arg.ID,
		arg.StudyID,
		arg.City,
		arg.State,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverLocation
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.City,
		&i.State,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverOutcomes = `-- name: CreateRowSilverOutcomes :one
INSERT INTO silver.outcomes(id,
study_id,
type,
measure,
timeframe,
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (study_id,type,measure)
DO UPDATE SET
    timeframe=EXCLUDED.timeframe,
    updated_at=now()
RETURNING id, study_id, type, measure, timeframe, created_at, updated_at
`

type CreateRowSilverOutcomesParams struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Type      string
	Measure   string
	Timeframe sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverOutcomes(ctx context.Context, arg CreateRowSilverOutcomesParams) (SilverOutcome, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverOutcomes,
		arg.ID,
		arg.StudyID,
		arg.Type,
		arg.Measure,
		arg.Timeframe,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverOutcome
	err := row.Scan(
		&i.ID,
		&i.StudyID,
		&i.Type,
		&i.Measure,
		&i.Timeframe,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverResponsibleParties = `-- name: CreateRowSilverResponsibleParties :one
INSERT INTO silver.responsible_parties(study_id,
type,
investigator_name,
investigator_title,
investigator_affiliation,
created_at,
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (study_id)
DO UPDATE SET 
    type=EXCLUDED.type,
    investigator_name=EXCLUDED.investigator_name,
    investigator_title=EXCLUDED.investigator_title,
    investigator_affiliation=EXCLUDED.investigator_affiliation,
    updated_at=now()
RETURNING study_id, type, investigator_name, investigator_title, investigator_affiliation, created_at, updated_at
`

type CreateRowSilverResponsiblePartiesParams struct {
	StudyID                 uuid.UUID
	Type                    sql.NullString
	InvestigatorName        sql.NullString
	InvestigatorTitle       sql.NullString
	InvestigatorAffiliation sql.NullString
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) CreateRowSilverResponsibleParties(ctx context.Context, arg CreateRowSilverResponsiblePartiesParams) (SilverResponsibleParty, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverResponsibleParties,
		arg.StudyID,
		arg.Type,
		arg.InvestigatorName,
		arg.InvestigatorTitle,
		arg.InvestigatorAffiliation,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverResponsibleParty
	err := row.Scan(
		&i.StudyID,
		&i.Type,
		&i.InvestigatorName,
		&i.InvestigatorTitle,
		&i.InvestigatorAffiliation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverSponsors = `-- name: CreateRowSilverSponsors :one
INSERT INTO silver.sponsors(study_id,
name,
class, 
created_at, 
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (study_id)
DO UPDATE SET 
    class=EXCLUDED.class,
    updated_at=now()
RETURNING study_id, name, class, created_at, updated_at
`

type CreateRowSilverSponsorsParams struct {
	StudyID   uuid.UUID
	Name      string
	Class     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowSilverSponsors(ctx context.Context, arg CreateRowSilverSponsorsParams) (SilverSponsor, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverSponsors,
		arg.StudyID,
		arg.Name,
		arg.Class,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverSponsor
	err := row.Scan(
		&i.StudyID,
		&i.Name,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverStudyStatus = `-- name: CreateRowSilverStudyStatus :one
INSERT INTO silver.study_status_details(study_id,
overall_status,
why_stopped,
status_verified_date,
status_verified_date_precision,
created_at,
updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (study_id)
DO UPDATE SET 
    overall_status=EXCLUDED.overall_status,
    why_stopped=EXCLUDED.why_stopped,
    status_verified_date=EXCLUDED.status_verified_date,
    status_verified_date_precision=EXCLUDED.status_verified_date_precision,
    updated_at=now()
RETURNING study_id, overall_status, why_stopped, status_verified_date, status_verified_date_precision, created_at, updated_at
`

type CreateRowSilverStudyStatusParams struct {
	StudyID                     uuid.UUID
	OverallStatus               sql.NullString
	WhyStopped                  sql.NullString
	StatusVerifiedDate          sql.NullTime
	StatusVerifiedDatePrecision sql.NullString
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}

func (q *Queries) CreateRowSilverStudyStatus(ctx context.Context, arg CreateRowSilverStudyStatusParams) (SilverStudyStatusDetail, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverStudyStatus,
		arg.StudyID,
		arg.OverallStatus,
		arg.WhyStopped,
		arg.StatusVerifiedDate,
		arg.StatusVerifiedDatePrecision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverStudyStatusDetail
	err := row.Scan(
		&i.StudyID,
		&i.OverallStatus,
		&i.WhyStopped,
		&i.StatusVerifiedDate,
		&i.StatusVerifiedDatePrecision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRowSilverUpsertStudies = `-- name: CreateRowSilverUpsertStudies :one
INSERT INTO silver.studies (
    id,
    nct_id,
    condition,
    study_type,
    phase,
    enrollment,
    start_date,
    start_date_precision,
    primary_completion_date,
    primary_completion_date_precision,
    completion_date,
    completion_date_precision,
    first_submit_date,
    first_submit_date_precision,
    last_update_submit_date,
    last_update_submit_date_precision,
    has_results,
    created_at,
    updated_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
ON CONFLICT (nct_id)
DO UPDATE SET
    study_type = EXCLUDED.study_type,
    phase = EXCLUDED.phase,
    enrollment = EXCLUDED.enrollment,

    start_date = EXCLUDED.start_date,
    start_date_precision = EXCLUDED.start_date_precision,

    primary_completion_date = EXCLUDED.primary_completion_date,
    primary_completion_date_precision = EXCLUDED.primary_completion_date_precision,

    completion_date = EXCLUDED.completion_date,
    completion_date_precision = EXCLUDED.completion_date_precision,

    first_submit_date = EXCLUDED.first_submit_date,
    first_submit_date_precision = EXCLUDED.first_submit_date_precision,

    last_update_submit_date = EXCLUDED.last_update_submit_date,
    last_update_submit_date_precision = EXCLUDED.last_update_submit_date_precision,

    has_results = EXCLUDED.has_results,
    updated_at = now()
RETURNING id, nct_id, condition, study_type, phase, enrollment, start_date, start_date_precision, primary_completion_date, primary_completion_date_precision, completion_date, completion_date_precision, first_submit_date, first_submit_date_precision, last_update_submit_date, last_update_submit_date_precision, has_results, created_at, updated_at
`

type CreateRowSilverUpsertStudiesParams struct {
	ID                             uuid.UUID
	NctID                          string
	Condition                      string
	StudyType                      sql.NullString
	Phase                          sql.NullString
	Enrollment                     sql.NullInt32
	StartDate                      sql.NullTime
	StartDatePrecision             sql.NullString
	PrimaryCompletionDate          sql.NullTime
	PrimaryCompletionDatePrecision sql.NullString
	CompletionDate                 sql.NullTime
	CompletionDatePrecision        sql.NullString
	FirstSubmitDate                sql.NullTime
	FirstSubmitDatePrecision       sql.NullString
	LastUpdateSubmitDate           sql.NullTime
	LastUpdateSubmitDatePrecision  sql.NullString
	HasResults                     sql.NullBool
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

func (q *Queries) CreateRowSilverUpsertStudies(ctx context.Context, arg CreateRowSilverUpsertStudiesParams) (SilverStudy, error) {
	row := q.db.QueryRowContext(ctx, createRowSilverUpsertStudies,
		arg.ID,
		arg.NctID,
		arg.Condition,
		arg.StudyType,
		arg.Phase,
		arg.Enrollment,
		arg.StartDate,
		arg.StartDatePrecision,
		arg.PrimaryCompletionDate,
		arg.PrimaryCompletionDatePrecision,
		arg.CompletionDate,
		arg.CompletionDatePrecision,
		arg.FirstSubmitDate,
		arg.FirstSubmitDatePrecision,
		arg.LastUpdateSubmitDate,
		arg.LastUpdateSubmitDatePrecision,
		arg.HasResults,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SilverStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.StudyType,
		&i.Phase,
		&i.Enrollment,
		&i.StartDate,
		&i.StartDatePrecision,
		&i.PrimaryCompletionDate,
		&i.PrimaryCompletionDatePrecision,
		&i.CompletionDate,
		&i.CompletionDatePrecision,
		&i.FirstSubmitDate,
		&i.FirstSubmitDatePrecision,
		&i.LastUpdateSubmitDate,
		&i.LastUpdateSubmitDatePrecision,
		&i.HasResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRowFromSilverStudiesByCondition = `-- name: GetRowFromSilverStudiesByCondition :one
SELECT id, nct_id, condition, study_type, phase, enrollment, start_date, start_date_precision, primary_completion_date, primary_completion_date_precision, completion_date, completion_date_precision, first_submit_date, first_submit_date_precision, last_update_submit_date, last_update_submit_date_precision, has_results, created_at, updated_at FROM silver.studies WHERE condition = $1
`

func (q *Queries) GetRowFromSilverStudiesByCondition(ctx context.Context, condition string) (SilverStudy, error) {
	row := q.db.QueryRowContext(ctx, getRowFromSilverStudiesByCondition, condition)
	var i SilverStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.StudyType,
		&i.Phase,
		&i.Enrollment,
		&i.StartDate,
		&i.StartDatePrecision,
		&i.PrimaryCompletionDate,
		&i.PrimaryCompletionDatePrecision,
		&i.CompletionDate,
		&i.CompletionDatePrecision,
		&i.FirstSubmitDate,
		&i.FirstSubmitDatePrecision,
		&i.LastUpdateSubmitDate,
		&i.LastUpdateSubmitDatePrecision,
		&i.HasResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRowFromSilverStudiesByID = `-- name: GetRowFromSilverStudiesByID :one
SELECT id, nct_id, condition, study_type, phase, enrollment, start_date, start_date_precision, primary_completion_date, primary_completion_date_precision, completion_date, completion_date_precision, first_submit_date, first_submit_date_precision, last_update_submit_date, last_update_submit_date_precision, has_results, created_at, updated_at FROM silver.studies WHERE id = $1
`

func (q *Queries) GetRowFromSilverStudiesByID(ctx context.Context, id uuid.UUID) (SilverStudy, error) {
	row := q.db.QueryRowContext(ctx, getRowFromSilverStudiesByID, id)
	var i SilverStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.StudyType,
		&i.Phase,
		&i.Enrollment,
		&i.StartDate,
		&i.StartDatePrecision,
		&i.PrimaryCompletionDate,
		&i.PrimaryCompletionDatePrecision,
		&i.CompletionDate,
		&i.CompletionDatePrecision,
		&i.FirstSubmitDate,
		&i.FirstSubmitDatePrecision,
		&i.LastUpdateSubmitDate,
		&i.LastUpdateSubmitDatePrecision,
		&i.HasResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRowFromSilverStudiesByNCTID = `-- name: GetRowFromSilverStudiesByNCTID :one
SELECT id, nct_id, condition, study_type, phase, enrollment, start_date, start_date_precision, primary_completion_date, primary_completion_date_precision, completion_date, completion_date_precision, first_submit_date, first_submit_date_precision, last_update_submit_date, last_update_submit_date_precision, has_results, created_at, updated_at FROM silver.studies WHERE nct_id = $1
`

func (q *Queries) GetRowFromSilverStudiesByNCTID(ctx context.Context, nctID string) (SilverStudy, error) {
	row := q.db.QueryRowContext(ctx, getRowFromSilverStudiesByNCTID, nctID)
	var i SilverStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.StudyType,
		&i.Phase,
		&i.Enrollment,
		&i.StartDate,
		&i.StartDatePrecision,
		&i.PrimaryCompletionDate,
		&i.PrimaryCompletionDatePrecision,
		&i.CompletionDate,
		&i.CompletionDatePrecision,
		&i.FirstSubmitDate,
		&i.FirstSubmitDatePrecision,
		&i.LastUpdateSubmitDate,
		&i.LastUpdateSubmitDatePrecision,
		&i.HasResults,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
