// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_bronze.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createRowBronze = `-- name: CreateRowBronze :one
INSERT INTO bronze.studies(id,nct_id,condition,raw_json,created_at,updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, nct_id, condition, raw_json, created_at, updated_at
`

type CreateRowBronzeParams struct {
	ID        uuid.UUID
	NctID     string
	Condition string
	RawJson   pqtype.NullRawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRowBronze(ctx context.Context, arg CreateRowBronzeParams) (BronzeStudy, error) {
	row := q.db.QueryRowContext(ctx, createRowBronze,
		arg.ID,
		arg.NctID,
		arg.Condition,
		arg.RawJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BronzeStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.RawJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRowByCondition = `-- name: GetRowByCondition :one
SELECT id, nct_id, condition, raw_json, created_at, updated_at FROM bronze.studies WHERE condition = $1
`

func (q *Queries) GetRowByCondition(ctx context.Context, condition string) (BronzeStudy, error) {
	row := q.db.QueryRowContext(ctx, getRowByCondition, condition)
	var i BronzeStudy
	err := row.Scan(
		&i.ID,
		&i.NctID,
		&i.Condition,
		&i.RawJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
