// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type BronzeStudy struct {
	ID        uuid.UUID
	NctID     string
	Condition string
	RawJson   pqtype.NullRawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GoldStudiesByPhaseOverTime struct {
	Year         int64
	Phase        sql.NullString
	TotalStudies int64
}

type SilverCollaborator struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Name      string
	Class     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverDesignDetail struct {
	StudyID           uuid.UUID
	Allocation        sql.NullString
	InterventionModel sql.NullString
	PrimaryPurpose    sql.NullString
	Masking           sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SilverEligibility struct {
	StudyID   uuid.UUID
	Sex       sql.NullString
	StdAges   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverIntervention struct {
	ID          uuid.UUID
	StudyID     uuid.UUID
	Type        string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SilverLocation struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	City      sql.NullString
	State     sql.NullString
	Country   sql.NullString
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverOutcome struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Type      string
	Measure   string
	Timeframe sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverReference struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Pmid      sql.NullString
	Type      sql.NullString
	Citation  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverResponsibleParty struct {
	StudyID                 uuid.UUID
	Type                    sql.NullString
	InvestigatorName        sql.NullString
	InvestigatorTitle       sql.NullString
	InvestigatorAffiliation sql.NullString
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type SilverSponsor struct {
	StudyID   uuid.UUID
	Name      string
	Class     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverStudy struct {
	ID                             uuid.UUID
	NctID                          string
	Condition                      string
	Title                          sql.NullString
	StudyType                      sql.NullString
	Phase                          sql.NullString
	Enrollment                     sql.NullInt32
	StartDate                      sql.NullTime
	StartDatePrecision             sql.NullString
	PrimaryCompletionDate          sql.NullTime
	PrimaryCompletionDatePrecision sql.NullString
	CompletionDate                 sql.NullTime
	CompletionDatePrecision        sql.NullString
	FirstSubmitDate                sql.NullTime
	FirstSubmitDatePrecision       sql.NullString
	LastUpdateSubmitDate           sql.NullTime
	LastUpdateSubmitDatePrecision  sql.NullString
	HasResults                     sql.NullBool
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

type SilverStudyStatusDetail struct {
	StudyID                     uuid.UUID
	OverallStatus               sql.NullString
	WhyStopped                  sql.NullString
	StatusVerifiedDate          sql.NullTime
	StatusVerifiedDatePrecision sql.NullString
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}
