// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type BronzeStudy struct {
	ID        uuid.UUID
	NctID     string
	Condition string
	RawJson   pqtype.NullRawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverCollaborator struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Name      string
	Class     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverIntervention struct {
	ID          uuid.UUID
	StudyID     uuid.UUID
	Type        string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SilverLocation struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	City      sql.NullString
	State     sql.NullString
	Country   sql.NullString
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverOutcome struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Measure   string
	Timeframe sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverReference struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Pmid      sql.NullString
	Type      sql.NullString
	Citation  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverSponsor struct {
	ID        uuid.UUID
	StudyID   uuid.UUID
	Name      string
	Class     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverStudy struct {
	ID             uuid.UUID
	NctID          string
	Condition      string
	Title          sql.NullString
	StudyType      sql.NullString
	Phase          sql.NullString
	Enrollment     sql.NullInt32
	OverallStatus  sql.NullString
	StartDate      sql.NullTime
	CompletionDate sql.NullTime
	HasResults     sql.NullBool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
