services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=clinical_trials
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    image: ghcr.io/mucusscraper/clinical-trials-disease-analytics-pipeline/go-cli:latest
    command: >
      sh -c "goose -dir /app/sql/schema postgres
      \"postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME?sslmode=disable\" up"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=clinical_trials

  go-cli:
    image: ghcr.io/mucusscraper/clinical-trials-disease-analytics-pipeline/go-cli:latest
    container_name: go_app
    depends_on:
      - migrations
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=clinical_trials
    stdin_open: true
    tty: true
    volumes:
      - ./reports/outputs:/app/reports/outputs
      - ./sql/schema:/app/sql/schema

volumes:
  postgres_data: