DROP TABLE IF EXISTS bronze.multiple_sclerosis;
CREATE TABLE bronze.multiple_sclerosis (
	NCT_Number TEXT,
	Study_Title TEXT,
	Study_URL TEXT,
	Acronym TEXT,
	Study_Status TEXT,
	Brief_Summary TEXT,
	Study_Results TEXT,
	Conditions TEXT,
	Interventions TEXT,
	Primary_Outcome_Measures TEXT,
	Secondary_Outcome_Measures TEXT,
	Other_Outcome_Measures TEXT,
	Sponsor TEXT, 
	Collaborators TEXT,
	Sex TEXT,
	Age TEXT,
	Phases TEXT,
	Enrollment INT,
	Funder_Type TEXT,
	Study_Type TEXT,
	Study_Design TEXT,
	Other_IDs TEXT,
	Start_Date TEXT,
	Primary_Completion_Date TEXT,
	Completion_Date TEXT,
	First_Posted TEXT,
	Results_First_Posted TEXT,
	Last_Update_Posted TEXT,
	Locations TEXT,
	Study_Documents TEXT
);