name: cd

on:
  push:
    branches: [main]
    tags: 
      - 'v*'

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_PASSWORD }} 
      
      - name: Build and push Go image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.godocker
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/go-cli:latest
            ghcr.io/${{ github.repository }}/go-cli:${{ env.VERSION }}

      - name: Build and push Python image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.pydocker
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/python-reports:latest
            ghcr.io/${{ github.repository }}/python-reports:${{ env.VERSION }}